import {createSpeechController} from './speech.js';
import {KEY,categories,normalize,validate,findWords,merge,nextReview} from './model.js';
const app=document.querySelector('#app'),dialog=document.querySelector('#detail');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data={app:'wordeer',version:1,words:[],pending:[]},dict=null,loadError='',storageError=false,filter='全部',query='',review=null,timer;
try{const raw=localStorage.getItem(KEY);if(raw)data=validate(JSON.parse(raw));}catch{storageError=true;loadError='浏览器词库无法读取。请勿清除数据，可先导出原始备份。';}
function save(next){if(storageError)throw Error('当前词库无法读取，已停止写入以保护原数据');localStorage.setItem(KEY,JSON.stringify(next));data=next;}
function toast(s){clearTimeout(timer);const t=document.querySelector('#toast');t.textContent=s;t.style.display='block';timer=setTimeout(()=>t.style.display='none',3600);}
function page(){return location.hash.slice(1)||'home';}
const due=()=>data.words.filter(w=>w.due<=Date.now());
function wordRows(words){return words.length?words.map(w=>`<article class="word"><button class="open" data-detail="${esc(w.term)}"><span class="term">${esc(w.term)}</span><span class="meaning">${esc(w.meaning)}</span></button><button class="star ${w.favorite?'active':''}" data-star="${esc(w.term)}" aria-label="${w.favorite?'取消收藏':'收藏'} ${esc(w.term)}">${w.favorite?'★':'☆'}</button></article>`).join(''):'<div class="empty"><div class="symbol">▤</div>这里还没有单词<br>从首页收录你的第一个英文单词</div>';}
function render(){document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+page()));
 if(page()==='home')app.innerHTML=`<section class="hero"><h1>让每一次遇见，<br>都成为你的词汇。</h1><div class="muted">Capture a word. Keep a little wonder.</div><div class="stats"><div class="stat"><b>${data.words.length}</b><span>已收录单词</span></div><div class="stat"><b>${due().length}</b><span>待复习</span></div><div class="stat"><b>${data.words.filter(w=>w.favorite).length}</b><span>我的收藏</span></div></div></section><section class="panel"><div class="row"><h3>✧ 遇见新单词</h3><button class="link" data-action="bulk">批量收词</button></div><form id="collect"><input class="input" name="term" autocomplete="off" autocapitalize="none" maxlength="2000" placeholder="输入单词或短语，如 serendipity" aria-label="要收录的英文"><button class="primary full" ${!dict?'disabled':''}>${dict?'查看单词卡':'词典加载中…'}</button></form><small class="note">${loadError?esc(loadError):'本地词典优先 · 自动归入对应单词本'}</small>${!dict&&loadError?'<button class="link" data-action="retry">重新加载词典</button>':''}</section><div class="row"><h2>我的单词本</h2><a class="link" href="#library">查看全部 ›</a></div><div class="grid">${categories.slice(0,4).map((c,i)=>`<button class="book" data-category="${c}"><span class="icon">${['▤','↗','✧','≈'][i]}</span><b>${c}</b><small>${data.words.filter(w=>w.category===c).length} 个单词</small><i>›</i></button>`).join('')}</div><div class="row"><h2>最近收录</h2><a class="link" href="#library">全部 ›</a></div>${wordRows([...data.words].reverse().slice(0,4))}`;
 else if(page()==='library'){app.innerHTML=`<h1>我的词库</h1><p class="muted">每一个单词，都值得留下。</p><input class="input" id="search" placeholder="搜索英文或中文释义" aria-label="搜索词库" value="${esc(query)}"><div class="filters">${['全部','收藏',...categories].map(c=>`<button class="chip ${filter===c?'active':''}" data-filter="${c}">${c}</button>`).join('')}</div><div id="word-list"></div>`;renderList();}
 else if(page()==='review')renderReview();
 else if(page()==='settings')app.innerHTML=`<section class="hero"><h1>我的 Wordeer</h1><div class="muted">一点一滴，让英语成为日常。</div></section><section class="panel"><h3>词库与数据</h3><button class="settings-button" data-action="pending">待处理输入 <span class="muted">${data.pending.length} 条</span>　›</button><button class="settings-button" data-action="export">导出词库备份　↓</button><button class="settings-button" data-action="restore">导入并合并备份　↑</button></section><section class="panel"><h3>关于网页测试版</h3><p class="muted">支持文字查词、自动分类、收藏、闪卡与选择题复习。词典包含 26,284 个词条及词形还原。</p><p class="muted">数据保存在当前浏览器，暂不跨设备同步。清理网站数据前请导出备份。</p><p class="muted">网页录音使用浏览器语音识别服务，可能需要联网并由浏览器服务处理音频。Action Button 仍需原生 App。DeepSeek 尚未连接，未命中的词会进入待处理。</p><button class="link" data-action="licenses">开源词典与字体许可</button></section>`;
 else{location.hash='home';return;}
}
function renderList(){let words=data.words.filter(w=>(filter==='全部'||(filter==='收藏'?w.favorite:w.category===filter))&&(!query||w.term.toLowerCase().includes(query.toLowerCase())||w.meaning.includes(query)));document.querySelector('#word-list').innerHTML=`<p class="muted">${words.length} 个单词</p>${wordRows([...words].reverse())}`;}
function show(html){dialog.innerHTML=`<button class="close" data-action="close" aria-label="关闭">×</button>${html}`;if(!dialog.open)dialog.showModal();}
let previewWord=null;
function wordCard(w){
 previewWord=w;
 const saved=data.words.find(x=>x.term===w.term);
 const examples=(Array.isArray(w.examples)?w.examples:(w.example?[w.example]:[])).filter(x=>typeof x==='string'&&x.trim()).slice(0,3);
 const related=Array.isArray(w.related)?w.related.filter(x=>x&&typeof x.term==='string'&&typeof x.explanation==='string'):[];
 show(`<div class="word-card"><span class="tag">${esc(w.category)}</span><p class="term">${esc(w.term)}</p>${w.phonetic?`<span class="muted">${esc(w.phonetic)}</span>`:''}<section><h3>中文释义</h3><p>${esc(w.meaning)}</p></section>${w.nuance?`<section><h3>语感与用法</h3><p>${esc(w.nuance)}</p></section>`:''}${examples.length?`<section><h3>例句</h3>${examples.map((text,i)=>`<p class="example"><span>${i+1}</span>${esc(text)}</p>`).join('')}</section>`:''}${related.length?`<section><h3>相近与关联词</h3>${related.map(x=>`<p><b>${esc(x.term)}</b><br>${esc(x.explanation)}</p>`).join('')}</section>`:''}${!w.nuance||examples.length<3||!related.length?'<small class="note">当前展示本地词典已有内容，完整语感、3 个例句与关联词解说待补充。</small>':''}<div class="card-actions">${saved?`<button class="secondary full" data-star="${esc(w.term)}">${saved.favorite?'★ 已收藏 · 点击取消':'☆ 收藏这个单词'}</button><p class="muted">已收录 · ${esc(saved.category)} · 已复习 ${saved.reviews} 次</p>`:`<button class="primary full" data-action="save-card">收录到「${esc(w.category)}」</button>`}</div></div>`);
}
function detail(term){const saved=data.words.find(w=>w.term===term);if(!saved)return;const local=dict?findWords(dict,term).find(w=>w.term===term):null;wordCard({...saved,...local});}
async function collect(text){if(!dict)throw Error('词典正在加载，请稍后');if(!normalize(text))return;const matches=findWords(dict,text);if(matches.length>1){show(`<h3>选择要收录的原形</h3>${matches.map(w=>`<button class="settings-button" data-pick="${esc(w.term)}"><b>${esc(w.term)}</b><span class="meaning">${esc(w.meaning)}</span></button>`).join('')}`);return;}
 if(!matches.length){const pending=[...new Set([...data.pending,text.trim()])];save({...data,pending});toast('本地词典未命中，已保存到待处理');render();return;}
 wordCard(matches[0]);}
function addWord(w){if(data.words.some(x=>x.term===w.term)){toast('已经收录，保留原有学习进度');return;}save({...data,words:[...data.words,{...w,created:Date.now(),favorite:0,reviews:0,level:0,due:0}],pending:data.pending.filter(p=>normalize(p)!==w.term)});toast(`已收录 ${w.term} · ${w.category}`);render();}
function renderReview(){if(!review){app.innerHTML=`<h1>温故，遇见新知</h1><p class="muted">每天一点，让单词真正属于你。</p><section class="review-card"><div class="muted">今天待复习</div><div class="term" style="color:#2f7bff;font-size:56px">${due().length}</div><div class="muted">共收录 ${data.words.length} 个单词</div></section><div class="choices"><button class="primary" data-action="flash" ${!data.words.length?'disabled':''}>开始闪卡复习</button><button class="secondary" data-action="quiz" ${data.words.length<4?'disabled':''}>四选一练习</button></div><p class="muted">选择题需要至少 4 个单词。没有到期单词时，可练习全部词库。</p>`;return;}
 const w=review.words[review.index];if(!w){app.innerHTML=`<section class="review-card"><div style="font-size:45px">✓</div><h1>本轮复习完成</h1><p class="muted">复习了 ${review.words.length} 个单词<br>掌握 ${review.correct} 个，继续积累。</p><button class="primary" data-action="end-review">返回复习</button></section>`;return;}
 app.innerHTML=`<div class="row"><h1>${review.mode==='flash'?'闪卡复习':'四选一练习'}</h1><button class="link" data-action="end-review">退出</button></div><p class="muted">${review.index+1} / ${review.words.length}</p><div class="progress"><span style="width:${review.index/review.words.length*100}%"></span></div><section class="review-card"><span class="term">${esc(w.term)}</span><span class="muted">${esc(w.phonetic)}</span>${review.revealed?`<p>${esc(w.meaning)}</p>`:''}</section>${review.mode==='flash'?(review.revealed?'<div class="row spaced"><button class="secondary full" data-grade="0">再学一次</button><button class="primary full" data-grade="1">记住了</button></div>':'<button class="primary full spaced" data-action="flip">查看释义</button>'):`<div class="choices">${review.options.map((o,i)=>`<button class="choice" data-answer="${i}" ${review.answered?'disabled':''}>${esc(o.meaning)}</button>`).join('')}</div>${review.answered?`<p class="answer">${review.wasCorrect?'回答正确':'正确释义：'+esc(w.meaning)}</p><button class="primary full" data-action="next">下一个</button>`:''}`}`;}
function options(){const w=review.words[review.index];if(!w)return;review.options=[w,...data.words.filter(x=>x.term!==w.term).sort(()=>Math.random()-.5).slice(0,3)].sort(()=>Math.random()-.5);}
function grade(correct){const w=review.words[review.index];save({...data,words:data.words.map(x=>x.term===w.term?{...x,reviews:x.reviews+1,level:correct?x.level+1:0,due:nextReview(x.level,correct)}:x)});if(correct)review.correct++;}
function advance(){review.index++;review.revealed=false;review.answered=false;options();renderReview();}
async function action(a){if(a==='save-card'){if(previewWord){addWord(previewWord);wordCard(previewWord);}return;}if(a==='record-entry'){if(!dict){toast('请等词典加载完成后录音');return;}speech.toggle();return;}if(a==='text-entry'){dialog.close();location.hash='home';render();document.querySelector('[name="term"]')?.focus();return;}if(a==='close'){dialog.close();return;}if(a==='retry'){loadDictionary();return;}if(a==='bulk'){show('<h3>批量收词</h3><p class="muted">每行一个单词或短语，最多 100 行。</p><form id="bulk"><textarea rows="7" name="terms" required placeholder="apple\ncurious\nlook forward to"></textarea><button class="primary full spaced">查词并收录</button></form>');}
 if(a==='pending')show(`<h3>待处理输入</h3><p class="muted">本地未命中的输入；AI 服务尚未连接。</p>${data.pending.length?data.pending.map(t=>`<div class="word"><span>${esc(t)}</span></div>`).join(''):'<p class="empty">暂无待处理内容</p>'}`);
 if(a==='export'){const blob=new Blob([storageError?localStorage.getItem(KEY):JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Wordeer-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),10000);toast('已生成词库备份');}
 if(a==='restore')show('<h3>导入 Wordeer 备份</h3><p class="muted">合并单词，已有单词的学习进度保留。</p><input id="restore-file" type="file" accept=".json,application/json" aria-label="选择 Wordeer 备份">');
 if(a==='licenses')show('<h3>开源许可</h3><p><a href="assets/ECDICT-LICENSE.txt" target="_blank">ECDICT · MIT License ↗</a></p><p><a href="assets/NotoSansSC-OFL.txt" target="_blank">Noto Sans SC · SIL OFL ↗</a></p>');
 if(a==='flash'||a==='quiz'){review={words:(due().length?due():[...data.words]).slice(0,20),index:0,mode:a,correct:0,revealed:false};options();renderReview();}if(a==='flip'){review.revealed=true;renderReview();}if(a==='end-review'){review=null;render();}if(a==='next')advance();}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;try{if(b.dataset.action)await action(b.dataset.action);if(b.dataset.category){filter=b.dataset.category;location.hash='library';}if(b.dataset.filter){filter=b.dataset.filter;render();}if(b.dataset.detail)detail(b.dataset.detail);if(b.dataset.star){save({...data,words:data.words.map(w=>w.term===b.dataset.star?{...w,favorite:w.favorite?0:1}:w)});render();if(dialog.open)detail(b.dataset.star);}if(b.dataset.pick){wordCard(findWords(dict,b.dataset.pick)[0]);}if(b.dataset.grade){grade(b.dataset.grade==='1');advance();}if(b.dataset.answer!==undefined&&!review.answered){const correct=review.options[Number(b.dataset.answer)].term===review.words[review.index].term;grade(correct);review.answered=true;review.wasCorrect=correct;renderReview();}}catch(err){toast(err.message||'操作失败，请重试');}});
document.addEventListener('submit',async e=>{e.preventDefault();try{if(e.target.id==='collect'){await collect(new FormData(e.target).get('term'));}if(e.target.id==='bulk'){if(!dict)throw Error('词典正在加载');const lines=[...new Set(new FormData(e.target).get('terms').split(/\r?\n/).map(s=>s.trim()).filter(Boolean))];if(lines.length>100)throw Error('每次最多导入 100 行');let words=[...data.words],pending=[...data.pending],added=0;for(const line of lines){const matches=findWords(dict,line);if(matches.length===1){const w=matches[0];if(!words.some(x=>x.term===w.term)){words.push({...w,created:Date.now(),favorite:0,reviews:0,level:0,due:0});added++;}pending=pending.filter(p=>normalize(p)!==normalize(line));}else pending.push(line);}save({...data,words,pending:[...new Set(pending)]});dialog.close();render();toast(`收录 ${added} 个单词，未命中或有歧义的输入保留在待处理`);}}catch(err){toast(err.message||'保存失败，请重试');}});
document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;renderList();}});
document.addEventListener('change',async e=>{if(e.target.id==='restore-file'){try{const f=e.target.files[0];if(!f)return;if(f.size>20*1024*1024)throw Error('备份文件过大');const next=merge(data,JSON.parse(await f.text()));save(next);dialog.close();render();toast('备份已合并');}catch(err){toast(err.message||'无法导入备份');}}});
window.addEventListener('hashchange',render);window.addEventListener('storage',e=>{if(e.key===KEY){try{data=e.newValue?validate(JSON.parse(e.newValue)):{app:'wordeer',version:1,words:[],pending:[]};review=null;render();}catch{toast('其他页面的数据无法读取，请重新打开');}}});
async function loadDictionary(){try{loadError='';const response=await fetch('assets/dictionary-web.json');if(!response.ok)throw Error();dict=await response.json();render();}catch{loadError='词典加载失败，请检查网络后重试。';render();}}
const recordButton=document.querySelector('.record-entry');
const micIcon=recordButton.querySelector('.record-circle').innerHTML;
const speech=createSpeechController({Recognition:window.SpeechRecognition||window.webkitSpeechRecognition,
 onState(state){const active=state!=='idle';recordButton.classList.toggle('recording',active);recordButton.setAttribute('aria-pressed',String(active));recordButton.setAttribute('aria-label',active?'停止录音并识别':'开始录音收词');recordButton.querySelector('.record-circle').innerHTML=active?'■':micIcon;recordButton.lastElementChild.textContent=({idle:'录音收词',starting:'启动中·点此停止',recording:'点击停止',stopping:'正在识别…'})[state];recordButton.disabled=state==='stopping';if(state==='recording')toast('正在录音，请说英语，再点录音键停止');},
 async onText(text){try{const matches=findWords(dict,text);if(matches.length){await collect(text);}else{save({...data,pending:[...new Set([...data.pending,text])]});show(`<h3>识别结果</h3><p class="term">${esc(text)}</p><p class="muted">本地未找到对应词条，已保存到待处理。可修改识别文字后再查词。</p><form id="voice-edit"><input class="input" name="term" value="${esc(text)}" aria-label="修改识别文字"><button class="primary full spaced">查看单词卡</button></form>`);render();}}catch(err){toast(err.message||'查词失败，请重试');}},
 onError(message){toast(message);}
});
document.addEventListener('submit',async e=>{if(e.target.id==='voice-edit'){e.preventDefault();try{await collect(new FormData(e.target).get('term'));}catch(err){toast(err.message);}}});
window.addEventListener('pagehide',()=>speech.cancel());
document.addEventListener('visibilitychange',()=>{if(document.hidden)speech.cancel();});
render();loadDictionary();
